packages:
- "workspaces/*"
- "workspaces/apps/*"
- "workspaces/apps/web/*"
- "workspaces/apps/web/docs/*"
- "workspaces/packages/local/*"
- "workspaces/packages/shared/*"
- "workspaces/packages/shared/templates/*"
- "workspaces/packages/shared/tsconfigs/*"
- "workspaces/packages/shared/esconfigs/"
- "workspaces/packages/shared/web/*"
- "workspaces/scripts/*"
- "workspaces/bin/*"
- "packages/shared/*"
- "apps/*"
