packages:
- "workspaces/*"
- "workspaces/apps/*"
- "workspaces/apps/web/*"
- "workspaces/apps/web/docs/*"
- "workspaces/packages/*"
- "workspaces/packages/templates/*"
- "workspaces/packages/tsconfigs/*"
- "workspaces/packages/esconfigs/"
- "workspaces/packages/web/*"
- "workspaces/scripts/*"
- "workspaces/bin/*"
- "packages/*"
- "apps/*"
